server:
  port: 8091
# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.host}:${mysql.port}/big_market?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 0
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    timeout: 10000
    pool-size: 10
    min-idle-size: 5
    idle-timeout: 30000
    connect-timeout: 5000
    retry-attempts: 3
    retry-interval: 1000
    ping-interval: 60000
    keep-alive: true
jetcache:
  statIntervalMinutes: 15          # 统计间隔（命中率、QPS）
  areaInCacheName: false           # cacheName 是否带 area 前缀

  local:
    default:
      type: caffeine          # 本地缓存类型
      keyConvertor: fastjson2      # key 序列化方式
      limit: 1000                  # 本地缓存最大条目数

  remote:
    default:
      type: redisson               # ⭐ 使用 redisson
      keyConvertor: fastjson2
      valueEncoder: java           # value 序列化（推荐 kryo）
      valueDecoder: java
      broadcastChannel: jetcache-broadcast

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

